INSERT INTO iceberg.bronze.hm_articles
SELECT
    CAST(NULLIF(article_id, '') AS BIGINT) AS article_id,
    CAST(NULLIF(product_code, '') AS BIGINT) AS product_code,
    NULLIF(prod_name, '') AS prod_name,
    CAST(NULLIF(product_type_no, '') AS INTEGER) AS product_type_no,
    NULLIF(product_type_name, '') AS product_type_name,
    NULLIF(product_group_name, '') AS product_group_name,
    CAST(NULLIF(graphical_appearance_no, '') AS INTEGER) AS graphical_appearance_no,
    NULLIF(graphical_appearance_name, '') AS graphical_appearance_name,
    CAST(NULLIF(colour_group_code, '') AS INTEGER) AS colour_group_code,
    NULLIF(colour_group_name, '') AS colour_group_name,
    CAST(NULLIF(perceived_colour_value_id, '') AS INTEGER) AS perceived_colour_value_id,
    NULLIF(perceived_colour_value_name, '') AS perceived_colour_value_name,
    CAST(NULLIF(perceived_colour_master_id, '') AS INTEGER) AS perceived_colour_master_id,
    NULLIF(perceived_colour_master_name, '') AS perceived_colour_master_name,
    CAST(NULLIF(department_no, '') AS INTEGER) AS department_no,
    NULLIF(department_name, '') AS department_name,
    NULLIF(index_code, '') AS index_code,
    NULLIF(index_name, '') AS index_name,
    CAST(NULLIF(index_group_no, '') AS INTEGER) AS index_group_no,
    NULLIF(index_group_name, '') AS index_group_name,
    CAST(NULLIF(section_no, '') AS INTEGER) AS section_no,
    NULLIF(section_name, '') AS section_name,
    CAST(NULLIF(garment_group_no, '') AS INTEGER) AS garment_group_no,
    NULLIF(garment_group_name, '') AS garment_group_name,
    NULLIF(detail_desc, '') AS detail_desc,
    CURRENT_TIMESTAMP AS ingest_ts,
    '__SOURCE_FILE_NAME__' AS source_file_name,
    '__BATCH_ID__' AS batch_id
FROM hive.raw.hm_articles_raw
